name: Build
on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  linux-cabal:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['8.6', '8.8', '8.10']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      name: Cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-store
    - uses: actions/setup-haskell@v2
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: '3.2'
    - name: Update cabal package database
      run: cabal update
    - name: Build
      run: |
        cabal build all

