name: Build
on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        ghc: ['8.6', '8.8', '8.10', '9.0']
        exclude:
        - os: windows-latest
          ghc: "8.8"
        - os: windows-latest
          ghc: "8.10"
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      if: ${{ runner.os == 'Windows' }}
      with:
        update: true
        install: zlib
    - uses: haskell/actions/setup@v1
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: '3.2'
    - name: Update cabal package database
      run: |
        cabal update
        cabal freeze
    - uses: actions/cache@v3.0.8
      name: Cache cabal stuff
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-
    - name: Build
      run: |
        cabal build all
    - name: SDist
      run: |
        cabal sdist all


